web-build:
  extends: .build
  rules:
    - if: '$BUILD'
    - if: '$REGIONS == "" || $REGIONS == null'

web-deploy:
  extends: .deploy
  needs:
    - web-build
    - if: '$REGIONS == "" || $REGIONS == null'
  rules:
    - if: '$BUILD != null && $BUILD != "" && $BUILD != "prod" && $BUILD != "prod-2"'

prod-web-deploy:
  extends: .deploy
  needs:
    - web-build
  rules:
    - if: '$BUILD == "prod"'
    - if: '$BUILD == "prod-2"'
    - if: '$REGIONS == "" || $REGIONS == null'
  after_script:
    - docker push $DOCKER_IMAGE_REPO:$TAG
    - docker tag $DOCKER_IMAGE_REPO:$TAG $DOCKER_IMAGE_REPO:$CI_COMMIT_TAG
    - docker push $DOCKER_IMAGE_REPO:$CI_COMMIT_TAG
