web-build:
  extends: .build
  before_script: []
  rules:
    - if: '$BUILD && ($REGIONS == "" || $REGIONS == null)'

web-deploy:
  extends: .deploy
  needs:
    - web-build
  rules:
    - if: '$BUILD != null && $BUILD != "" && $BUILD != "prod" && $BUILD != "prod-2" && ($REGIONS == "" || $REGIONS == null)'

prod-web-deploy:
  extends: .deploy
  needs:
    - web-build
  rules:
    - if: '($BUILD == "prod" || $BUILD == "prod-2") && ($REGIONS == "" || $REGIONS == null)'
  after_script:
    - docker push $DOCKER_IMAGE_REPO:$TAG
    - docker tag $DOCKER_IMAGE_REPO:$TAG $DOCKER_IMAGE_REPO:$CI_COMMIT_TAG
    - docker push $DOCKER_IMAGE_REPO:$CI_COMMIT_TAG
