web-build:
  extends: .build
  rules:
    - if: '$BUILD'

web-deploy:
  extends: .deploy
  needs:
    - web-build
  rules:
    - if: '$BUILD'
    - if: '$BUILD == "prod"'
      when: never
    - if: '$BUILD == "prod-2"'
      when: never

prod-web-deploy:
  extends: .deploy
  needs:
    - web-build
  rules:
    - if: '$BUILD == "prod"'
    - if: '$BUILD == "prod-2"'
  after_script:
    - docker push $DOCKER_IMAGE_REPO:$TAG
    - docker tag $DOCKER_IMAGE_REPO:$TAG $DOCKER_IMAGE_REPO:$CI_COMMIT_TAG
    - docker push $DOCKER_IMAGE_REPO:$CI_COMMIT_TAG
