include:
  - https://raw.githubusercontent.com/tickone/shared-configuration/master/gitlab-ci/gcr.yml
  - https://raw.githubusercontent.com/tickone/shared-configuration/master/gitlab-ci/template.yml
  - https://raw.githubusercontent.com/tickone/shared-configuration/master/gitlab-ci/regional-job.yml

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      variables:
        BUILD: prod
        TAG: stable
        DEV_PIPELINE: false
    - if: '$CI_COMMIT_BRANCH == "beta" && $CI_COMMIT_TAG !~ /^(|v)(?:0|(?:[1-9]\d*))\.(?:0|(?:[1-9]\d*))\.(?:0|(?:[1-9]\d*))(?:-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?(?:\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$/'
      variables:
        BUILD: beta
        TAG: beta
    - if: '$CI_COMMIT_BRANCH == "beta" && $CI_COMMIT_TAG ~= /^(|v)(?:0|(?:[1-9]\d*))\.(?:0|(?:[1-9]\d*))\.(?:0|(?:[1-9]\d*))(?:-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?(?:\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$/'
      variables:
        BUILD: prod
        TAG: stable
        REGIONS: hk
        DEV_PIPELINE: false
stages:
  - pre
  - build
  - test
  - deploy
  - release

variables:
  DEV_PIPELINE: true
