include:
  - https://raw.githubusercontent.com/tickone/shared-configuration/master/gitlab-ci/gcr.yml
  - https://raw.githubusercontent.com/tickone/shared-configuration/master/gitlab-ci/template.yml
  - https://raw.githubusercontent.com/tickone/shared-configuration/master/gitlab-ci/regional-job.yml

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

stages:
  - pre
  - build
  - test
  - deploy
  - release

variables:
  BUILD: prod
  TAG: stable
  DEV_PIPELINE: true
