include:
  - https://raw.githubusercontent.com/tickone/shared-configuration/master/gitlab-ci/gcr.yml
  - https://raw.githubusercontent.com/tickone/shared-configuration/master/gitlab-ci/template.yml
  - https://raw.githubusercontent.com/tickone/shared-configuration/master/gitlab-ci/job.yml
  - https://raw.githubusercontent.com/tickone/shared-configuration/master/gitlab-ci/regional-job.yml

stages:
  - pre
  - build
  - test
  - deploy
  - release

variables:
  BUILD: prod

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
      variables:
        TAG: 'latest'
    - if: '$CI_COMMIT_BRANCH == "dev2"'
      variables:
        TAG: 'latest-2'
    - if: '$CI_COMMIT_BRANCH == "master"'
      variables:
        TAG: 'beta'
    - if: '$CI_COMMIT_BRANCH == "master2"'
      variables:
        TAG: 'beta-2'
    - if: '$CI_COMMIT_TAG =~ /^(|v)(?:0|(?:[1-9]\d*))\.(?:0|(?:[1-9]\d*))\.(?:0|(?:[1-9]\d*))(?:-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?(?:\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$/'
      variables:
        TAG: 'stable'
    - if: '$CI_COMMIT_BRANCH == "stable-2"'
      variables:
        TAG: stable-2
