include:
  - https://raw.githubusercontent.com/tickone/shared-configuration/master/gitlab-ci/gcr.yml
  - https://raw.githubusercontent.com/tickone/shared-configuration/master/gitlab-ci/template.yml
  - https://raw.githubusercontent.com/tickone/shared-configuration/master/gitlab-ci/regional-job.yml

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
      variables:
        BUILD: test
        TAG: latest
        REGIONS: hk,th
    - if: $CI_COMMIT_BRANCH == "master"
      variables:
        BUILD: prod
        TAG: stable
        REGIONS: th
    - if: '$CI_COMMIT_BRANCH == "beta"'
      variables:
        BUILD: beta
        TAG: beta
        REGIONS: hk,th
    - if: '$CI_COMMIT_BRANCH =~ /^feat\//'
      variables:
        BUILD: beta
        TAG: beta
        REGIONS: hk,th
    - if: $CI_COMMIT_BRANCH =~ /^feature\//'
      variables:
        BUILD: test
        TAG: latest
        REGIONS: hk,th
    - if: '$CI_COMMIT_TAG =~ /^(|v)(?:0|(?:[1-9]\d*))\.(?:0|(?:[1-9]\d*))\.(?:0|(?:[1-9]\d*))(?:-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?(?:\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$/'
      variables:
        BUILD: prod
        TAG: stable
        REGIONS: hk

stages:
  - pre
  - build
  - test
  - deploy
  - release
