# Regional deployment jobs for different regions
# This file handles region-specific builds and deployments
# Use REGIONS variable with comma-separated values like "th,sg,my,jp,kr" or any custom region codes

.regional-build:
  extends: .build
  script:
    - |
      if [ -n "$REGIONS" ]; then
        IFS=',' read -ra REGION_ARRAY <<< "$REGIONS"
        for region in "${REGION_ARRAY[@]}"; do
          echo "Building for region: $region"
          docker build . -t $DOCKER_IMAGE_REPO:$TAG-$region --build-arg GIT_USERNAME="${GIT_USERNAME}" --build-arg GIT_PASSWORD="${GIT_PASSWORD}" --build-arg BUILD="${BUILD}" --build-arg CI_COMMIT_SHA="${CI_COMMIT_SHA}" --build-arg APP_ENV="${APP_ENV}" --build-arg REACT_APP_REGION="$region"
          docker save $DOCKER_IMAGE_REPO:$TAG-$region > image-$region.tar
        done
      elif [ -n "$REGION" ]; then
        echo "Building for single region: $REGION"
        docker build . -t $DOCKER_IMAGE_REPO:$TAG-$REGION --build-arg GIT_USERNAME="${GIT_USERNAME}" --build-arg GIT_PASSWORD="${GIT_PASSWORD}" --build-arg BUILD="${BUILD}" --build-arg CI_COMMIT_SHA="${CI_COMMIT_SHA}" --build-arg APP_ENV="${APP_ENV}" --build-arg REACT_APP_REGION="$REGION"
        docker save $DOCKER_IMAGE_REPO:$TAG-$REGION > image-$REGION.tar
      fi
  rules:
    - if: '$REGIONS && $BUILD'
    - if: '$REGION && $BUILD'

.regional-deploy:
  extends: .deploy
  script:
    - |
      if [ -n "$REGIONS" ]; then
        IFS=',' read -ra REGION_ARRAY <<< "$REGIONS"
        for region in "${REGION_ARRAY[@]}"; do
          echo "Deploying for region: $region"
          docker load < image-$region.tar
          docker push $DOCKER_IMAGE_REPO:$TAG-$region
          if [ -n "$CI_COMMIT_TAG" ]; then
            docker tag $DOCKER_IMAGE_REPO:$TAG-$region $DOCKER_IMAGE_REPO:$CI_COMMIT_TAG-$region
            docker push $DOCKER_IMAGE_REPO:$CI_COMMIT_TAG-$region
          fi
        done
      elif [ -n "$REGION" ]; then
        echo "Deploying for single region: $REGION"
        docker load < image-$REGION.tar
        docker push $DOCKER_IMAGE_REPO:$TAG-$REGION
        if [ -n "$CI_COMMIT_TAG" ]; then
          docker tag $DOCKER_IMAGE_REPO:$TAG-$REGION $DOCKER_IMAGE_REPO:$CI_COMMIT_TAG-$REGION
          docker push $DOCKER_IMAGE_REPO:$CI_COMMIT_TAG-$REGION
        fi
      fi

# Dynamic regional build job
regional-web-build:
  extends: .regional-build

# Dynamic regional deploy job
regional-web-deploy:
  extends: .regional-deploy
  needs:
    - regional-web-build
