.build:
  stage: build
  script:
    - docker build . -t $DOCKER_IMAGE_REPO:$TAG --build-arg GIT_USERNAME="${GIT_USERNAME}" --build-arg GIT_PASSWORD="${GIT_PASSWORD}" --build-arg BUILD="${BUILD}" --build-arg CI_COMMIT_SHA="${CI_COMMIT_SHA}" --build-arg APP_ENV="${APP_ENV}"
    - docker save $DOCKER_IMAGE_REPO:$TAG > image.tar
  artifacts:
    paths:
      - image.tar
    expire_in: 1 day
  interruptible: true

.deploy:
  stage: deploy
  script:
    - docker load < image.tar
  after_script:
    - docker push $DOCKER_IMAGE_REPO:$TAG
